package `in`.nakkalites.mediaclient.app.constants

object AnalyticsConstants {
    object Event {
        const val APP_OPENED = "app_opened"
        const val LOGIN_FAILED = "login_failed"
        const val SIGN_UP_CTA_CLICKED = "sign_up_cta_clicked"
        const val WEBSERIES_PAGE_OPENED = "webseries_page_opened"
        const val WEBSERIES_SHARE_CLICKED = "webseries_share_clicked"
        const val WEBSERIES_PLAY_CTA_CLICKED = "webseries_play_cta_clicked"
        const val WEBSERIES_EPISODE_CLICKED = "webseries_episode_clicked"
        const val WEBSERIES_SEASONS_CLICKED = "webseries_seasons_clicked"
        const val VIDEO_GROUP_LIST_PAGE_OPENED = "video_group_list_page_opened"
        const val VIDEO_GROUP_LIST_VIDEO_CLICKED = "video_group_list_video_clicked"
        const val VIDEO_DETAIL_PAGE_OPENED = "video_detail_page_opened"
        const val VIDEO_DETAIL_VIDEO_CLICKED = "video_detail_video_clicked"
        const val VIDEO_DETAIL_PLAY_CTA_CLICKED = "video_detail_play_cta_clicked"
        const val VIDEO_DETAIL_SHARE_CTA_CLICKED = "video_detail_share_cta_clicked"
        const val VIDEO_PLAYER_PAGE_OPENED = "video_player_page_opened"
        const val VIDEO_PAUSED = "video_paused"
        const val TAB_OPENED = "%s_tab_clicked"
        const val HOME_VIDEO_GROUP_CLICKED = "home_video_group_clicked"
        const val HOME_VIDEO_CLICKED = "home_video_clicked"
        const val BANNER_CLICKED = "banner_clicked"
        const val EMAIL_CLICKED = "email_clicked"
        const val SHARE_CLICKED = "share_clicked"
        const val WEBSERIES_CLICKED = "webseries_clicked"
        const val AD_OPENED = "ad_opened"
        const val AD_CLOSED = "ad_closed"
        const val AD_FAILED_TO_LOAD = "ad_failed_to_load"
        const val MANAGE_SUBSCRIPTION_CLICKED = "manage_subscription_clicked"
        const val MANAGE_SUBSCRIPTION_CTA_CLICKED = "manage_subscription_cta_clicked"
        const val PROFILE_PLAN_CTA_CLICKED = "profile_plan_cta_clicked"
        const val PROFILE_EDIT_CLICKED = "profile_edit_clicked"
        const val FAQ_CLICKED = "faq_clicked"
        const val VERIFY_OTP_CLICKED = "verify_otp_clicked"
        const val RESEND_OTP_CLICKED = "resend_otp_clicked"
        const val PROFILE_ADD_SAVE_CLICKED = "profile_add_save_clicked"
        const val PROFILE_ADD_SUCCESS = "profile_add_success"
        const val PROFILE_ADD_FAILURE = "profile_add_failure"
        const val PROFILE_EDIT_SAVE_CLICKED = "profile_edit_save_clicked"
        const val PROFILE_EDIT_SUCCESS = "profile_edit_success"
        const val PROFILE_EDIT_FAILURE = "profile_edit_failure"
        const val VIDEO_CLICKED = "video_failure"
        const val PLAN_SELECTED = "plan_selected"
        const val PLAN_UPDATE_SUCCESS = "plan_update_success"
        const val PLAN_UPDATE_FAILURE = "plan_update_failure"
        const val RAZORPAY_SUCCESS = "razorpay_success"
        const val RAZORPAY_FAILURE = "razorpay_failure"
        const val PLAN_ORDER_FETCH_SUCCESS = "plan_order_fetch_success"
        const val PLAN_ORDER_FETCH_FAILURE = "plan_order_fetch_failure"
    }

    object Property {
        const val MANUFACTURER = "manufacturer"
        const val MODEL = "model"
        const val OS = "os"
        const val BRAND = "brand"
        const val OS_VERSION = "os_version"
        const val APP_VERSION_CODE = "app_version_code"
        const val APP_VERSION_NAME = "app_version_name"
        const val LAST_APP_OPENED = "last_app_opened"
        const val FIRST_SIGN_UP_DATE = "first_sign_up_date"
        const val INSTANCE_ID = "instance_id"
        const val USER_EMAIL = "user_email"
        const val USER_PHONE = "user_phone"
        const val USER_ID = "nakkalites_user_id"
        const val USER_NAME = "user_name"
        const val USER_IMAGE_URL = "user_image_url"
        const val WEBSERIES_ID = "webseries_id"
        const val CURRENT_PLAN = "current_plan"
        const val AVAILABLE_PLAN = "available_plan"
        const val SELECTED_PLAN = "selected_plan"
        const val IS_PLAYABLE = "is_playable"
        const val SHOW_ADS = "show_ads"
        const val WEBSERIES_NAME = "webseries_name"
        const val SEASON_NAME = "season_name"
        const val SEASON_ID = "season_id"
        const val VIDEO_GROUP_ID = "video_group_id"
        const val VIDEO_GROUP_NAME = "video_group_name"
        const val VIDEO_ID = "video_id"
        const val VIDEO_NAME = "video_name"
        const val VIDEO_DURATION = "video_duration"
        const val VIDEO_TIME_ELAPSED = "video_time_elapsed"
        const val BANNER_ID = "banner_id"
        const val BANNER_NAME = "banner_name"
        const val BANNER_TYPE = "banner_type"
        const val ERROR_MESSAGE = "error_message"
    }
}
